### ISSUE TITLE
[FORGE 1.16] Register DisplayTest extension point to prevent server list FML incompatibility notification

### ISSUE THREAD

**Issue by Mike5357** [Keksuccino/Konkrete#10]
Add ModLoadingContext to prevent multiplayer servers from displaying as incompatible if the mod is installed on the client.
See https://mcforge.readthedocs.io/en/1.16.x/concepts/sides/#writing-one-sided-mods

![image](https://user-images.githubusercontent.com/12630858/148651561-2d34ce30-747c-41d6-8eed-b543a9368485.png)

**Comment by Keksuccino** [comment]
Fixed in v1.3.3-1 for Forge 1.16.X. Thank you for your report!
