### ISSUE TITLE
Crashma modpack

### ISSUE THREAD

**Issue by TheButterbrotMan** [Keksuccino/Konkrete#13]
Minecraft: 1.18.2
Fabric: 0.18.4
Konkrete: konkrete_fabric_1.3.3-3_MC_1.18-1.18.2

I just start my modpack and then this: https://bytebin.lucko.me/7PTbvKrzRT

**Comment by Keksuccino** [comment]
Should be fixed in v1.3.3-4 for Fabric 1.18.X! Thank you for your report!
