### ISSUE TITLE
Client-sided command issue

### ISSUE THREAD

**Issue by Thrumptus** [Keksuccino/Konkrete#15]
When using Konkrete, client-sided commands aren't suggested and are marked as unknown or incomplete when entered, despite still functioning as normal

Minecraft Version: 1.19.2
Konkrete Version: 1.5.0

**Comment by Keksuccino** [comment]
- Fabric/Forge version
- `logs/latest.log` AFTER trying to type and send a command, please
- What client commands are you talking about exactly? Which mod are they from?

Thank you!

**Comment by skibidibada** [comment]
The mod is called "clientcommands"  https://github.com/Earthcomputer/clientcommands is the github, when using konkrete mod all commands that the clientcommands mod gives disappear fabric 1.19.2

**Comment by Thrumptus** [comment]
Sorry for the late response

Fabric version 0.14.9
The client commands are provided by the fabric api and https://github.com/Earthcomputer/clientcommands
I looked through and the log doesn't provide anything related to commands as they still function as normal

I didn't phrase it very well before, the commands still work as normal when run, but in the chat box they show up as red and aren't in the list of suggested commands

![image](https://user-images.githubusercontent.com/93964920/194765017-ffc6e6c9-1c2b-4003-a12b-73d701dc854c.png)

![image](https://user-images.githubusercontent.com/93964920/194766294-654799b1-d7bc-4cfe-a035-b22fd3de96b4.png)

**Comment by Keksuccino** [comment]
> The client commands are provided by https://github.com/Earthcomputer/clientcommands

So this is a mod incompatibility.

Well, I think that needs to get fixed in the other mod.

This is where I inject my client commands: [link to mixin](https://github.com/Keksuccino/Konkrete/blob/eb061a818dd6aca21861816675de10cb16e6ddf0/src/main/java/de/keksuccino/konkrete/mixin/mixins/client/MixinClientPacketListener.java#L34)

Since the commands of the other mod are still working, but aren't in the suggestions list anymore and get displayed in red, it looks like the other mod is injecting commands in a weird way (not sure about that, didn't check the code).

**Comment by Thrumptus** [comment]
Ok, thanks for clarifying, will take it up over there then

**Comment by haykam821** [comment]
Client Commands uses [the standard client command registration event](https://github.com/Earthcomputer/clientcommands/blob/fbe5bfc6bf6b6584a205df45217e76cd2544b2de/src/main/java/net/earthcomputer/clientcommands/ClientCommands.java#L23) to register its client commands. Therefore, this mod should make itself compatible with Fabric API, not vice versa.

**Comment by Keksuccino** [comment]
I didn't even know there's an event for that on Fabric! Thank you for telling me, will fix it in the next update :)

**Comment by Keksuccino** [comment]
Fixed in Konkrete v1.5.3! Thank you for your report!
