### ISSUE TITLE
Mixin Crash on load MC 1.20

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/Konkrete#16]
MC 1.20
Forge version: 46.0.14

Attempting to load up FMM/Konkrete results in a crash, logfile is here:

https://gist.github.com/Saereth/8208cf184a884749a028b0963326adbe

If you would like me to gather any additional information or run other tests let me know, thanks!

**Comment by Keksuccino** [comment]
Should be fixed now! Thank you for telling me!
