### ISSUE TITLE
mod“konkrete”中的命名空间不匹配

### ISSUE THREAD

**Issue by Eostrehold** [Keksuccino/Konkrete#17]
I am using your mod "konkrete" and encountering an error during the loading process, which prevents the game from starting. The error log shows the following exception:
```java
java.lang.RuntimeException: Failed to read accessWidener file from mod konkrete
...
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
``` 
Minecraft version: 1.20.1
Fabric Loader version: 0.14.21
"konkrete" mod version: 1.6.1
Other installed mods: Fabric API(0.85.0)mod

**Comment by Keksuccino** [comment]
Please send me the full log.

Also make sure you're using the correct JAR (not the dev jar).

**Comment by Ran-Yijiu** [comment]
This is my runtime log.
________________________________

**Comment by Eostrehold** [comment]
I re-subscribe and found that I downloaded the developer jar, and now I can use it and no error, sorry for the trouble.
