### ISSUE TITLE
game crashing instantly 1.17

### ISSUE THREAD

**Issue by ZeroTasteGuy1** [Keksuccino/Konkrete#2]
when i start my game i get an instant code 0 
mods used:
BetterThirdPerson - Fabric - 1.17 - 1.5.0
cr-compass-ribbon-fabric-2.7.2+1.17
WI-Zoom-1.3-MC1.17.jar
tweakeroo-fabric-1.17.0-0.10.0-dev.20210608.211857.jar
preview_OptiFine_1.17_HD_U_G9_pre20.jar
OptiFabric-v1.11.1
Mod Menu v2.0.2 for 1.17
minihud-fabric-1.17.0-0.19.0-dev.20210609.185508.jar
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1.jar
FancyMenu [Fabric] v2.1.1 MC 1.17

**Comment by ZeroTasteGuy1** [comment]
idk what else to write
so 
here is a screenshot i guess
![image](https://user-images.githubusercontent.com/84146863/122674699-9fd9f500-d1d6-11eb-80cc-c4f88fbb0fe4.png)

**Comment by ZeroTasteGuy1** [comment]
[latest.log](https://github.com/Keksuccino/Konkrete/files/6682347/latest.log)

**Comment by ZeroTasteGuy1** [comment]
i guess some of the mods are incompatible

**Comment by Keksuccino** [comment]
Maybe at least a log would help :)
Please send me your latest.log file, located at `.minecraft/logs/latest.log`.

Oh and there’s no Konkrete in your mod list. If that’s not a mistake, then it’s probably crashing because you don’t have all dependencies for FM.

//Edit: Well, you just sent the log, that’s good lmao

**Comment by ZeroTasteGuy1** [comment]
ok https://github.com/Keksuccino/Konkrete/issues/2#issuecomment-864549658 here is the log btw

**Comment by ZeroTasteGuy1** [comment]
ouuf the link didnt work

**Comment by ZeroTasteGuy1** [comment]
i just added konkrete but its still crashing 
[latest.log](https://github.com/Keksuccino/Konkrete/files/6682353/latest.log)
here is the newest log...

**Comment by ZeroTasteGuy1** [comment]
Oh, yeah I'm using GDlauncher, but I tried it with the normal one and it still crashed...

**Comment by Keksuccino** [comment]
Please try to load the game with only FancyMenu, Konkrete and Fabric API.

**Comment by ZeroTasteGuy1** [comment]
ok ill try
one sec

**Comment by ZeroTasteGuy1** [comment]
[mods.zip](https://github.com/Keksuccino/Konkrete/files/6682364/mods.zip)
here are all my mods if that helps...

**Comment by ZeroTasteGuy1** [comment]
game is starting

**Comment by ZeroTasteGuy1** [comment]
everything works without all the other mods

**Comment by Keksuccino** [comment]
Well, then it’s a mod conflict. You need to check which one is incompatible and remove either FM or the other mod. And please tell me which mod it is if you find it, so I can add it to the incompatibility list! :)

**Comment by ZeroTasteGuy1** [comment]
ok
thanks ill have fun checking that :\

**Comment by ZeroTasteGuy1** [comment]
its optifine :C

**Comment by ZeroTasteGuy1** [comment]
whyyyy

**Comment by Keksuccino** [comment]
Because nobody uses Optifine in fabric, I think? :D There are enough alternatives you can try. But did you tried to load your mod setup without FM and Konkrete? It is working without these, right?

**Comment by ZeroTasteGuy1** [comment]
ye

**Comment by ZeroTasteGuy1** [comment]
i have played a lot with them

**Comment by Keksuccino** [comment]
Okay, that’s good :) Well, I’m sorry, but you need to find an Optifine alternative or remove FM + dependencies to fix that. I don’t think I will fix Optifine incompatibilities on Fabric, because there’s no reason to even use that mod on Fabric, sorry..

**Comment by ZeroTasteGuy1** [comment]
wont*

**Comment by ZeroTasteGuy1** [comment]
and i already found one so everything is fine

**Comment by Keksuccino** [comment]
> wont*

?

**Comment by ZeroTasteGuy1** [comment]
![image](https://user-images.githubusercontent.com/84146863/122677194-8ab69380-d1e1-11eb-9c3b-beaee8e03a0b.png)
!

**Comment by Keksuccino** [comment]
Yeah, I don’t think I will fix them for Fabric, because there aren’t enough OptiFabric users. What’s wrong with it?

**Comment by ZeroTasteGuy1** [comment]
nothing i just corrected your sentence from "i will" to "i wont"

**Comment by ZeroTasteGuy1** [comment]
oh

**Comment by ZeroTasteGuy1** [comment]
i dumb

**Comment by ZeroTasteGuy1** [comment]
sry

**Comment by Keksuccino** [comment]
So first thing: My sentence was correct. 
Second: It’s just so rude to try correcting people you asked for help. I hate that.
