### ISSUE TITLE
Crash with multiple mods installed

### ISSUE THREAD

**Issue by Suatae** [Keksuccino/Konkrete#4]
I tried loading it in my modpack so I can have the latest FancyMenu but for some reason Konkrete is not working well with these mods specifically:

[crash-2021-07-17_14.48.01-client.txt](https://github.com/Keksuccino/Konkrete/files/6835357/crash-2021-07-17_14.48.01-client.txt)

**Comment by Keksuccino** [comment]
Hi!
This is not a direct issue with Konkrete, it's more like an issue with FancyMenu being incompatible with one of your core mods.
